### PR TITLE
fix: #106 Adding Support for Environment Agnostic Stacks

### LINKED ISSUE #106: Supporting Environment Agnostic Stacks
This construct does not currently support AWS CDK's [environment agnostic stacks](https://docs.aws.amazon.com/cdk/v2/guide/environments.html). Because AWS offers Amazon Managed Blockchain in specific regions and availability zones, validation at the construct level was prioritized in conception, which causes AWS CDK apps that do not set a specific `region` in the environment variables section to fail at `region` validation.

### PR DESCRIPTION
**Pull request by trinitykey**
Fixes #106 

Please reference [this issue](https://github.com/cdklabs/cdk-ethereum-node/pull/107).

### CODE REVIEW

File: src/node.ts [hunk 1]
```diff
@@ -97,10 +104,15 @@ export class EthereumNode extends constructs.Construct {
...
     this.network = props.network ?? Network.MAINNET;
     this.instanceType = props.instanceType ?? InstanceType.BURSTABLE3_LARGE;
-    this.availabilityZone = props.availabilityZone ?? `${region}a`;
 
-    utilities.validateRegion(region);
-    utilities.validateAvailabilityZone(region, this.availabilityZone);
+    // If no availability zone is provided, use the first in the region.
+    if (regionInEnvironment) {
+      utilities.validateRegion(region);
+      this.availabilityZone = props.availabilityZone ?? `${region}a`;
```
Comment (lordjabez) [inline src/node.ts:111]: Now that we have `region` as an output parameter we need to set it with `this.region = region;`

File: src/node.ts [hunk 2]
```diff
@@ -52,6 +52,11 @@ export interface EthereumNodeProps {
      */
   readonly instanceType?: InstanceType;
 
+  /**
+   * The Region in which the node will be created
```
Comment (lordjabez) [inline src/node.ts:56]: This should be down in the class itself, and the comment should be `The Region in which the node exists`

File: src/node.ts [hunk 3]
```diff
@@ -97,10 +104,15 @@ export class EthereumNode extends constructs.Construct {
...
 
-    utilities.validateRegion(region);
-    utilities.validateAvailabilityZone(region, this.availabilityZone);
+    // If no availability zone is provided, use the first in the region.
+    if (regionInEnvironment) {
+      utilities.validateRegion(region);
+      this.availabilityZone = props.availabilityZone ?? `${region}a`;
+      utilities.validateAvailabilityZone(region, this.availabilityZone);
+    } else {
+      this.availabilityZone = props.availabilityZone ?? availabilityZones[0];
```
Comment (lordjabez) [inline src/node.ts:114]: And again: `this.region = regions[0];` (I think this will work?)

File: src/node.ts [hunk 4]
```diff
@@ -115,4 +127,4 @@ export class EthereumNode extends constructs.Construct {
 
   }
 
-}
+}
```
Comment (lordjabez) [inline src/node.ts:130]: A minor thing, but can you have your editor preserve the final line break?

**Review by lordjabez — CHANGES_REQUESTED** [review]

File: src/node.ts (hunk 2 above)
Comment (trinitykey) [reply src/node.ts:56]: I originally had it in the class, but I must have moved it incorrectly when I reset my branch. I moved it and reformatted the comment!

File: src/node.ts (hunk 1 above)
Comment (trinitykey) [reply src/node.ts:112]: Resolved

File: src/node.ts (hunk 3 above)
Comment (trinitykey) [reply src/node.ts:115]: I set the region once before evaluating the if statement instead of in both conditionals because either way, the region will either be assigned a single token or a single string.

File: src/node.ts (hunk 1 above)
Comment (lordjabez) [reply src/node.ts:112]: Yes, I just missed it!

**Review by lordjabez — APPROVED** [review]
